# Generated by Django 4.0.4 on 2022-05-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название галактики')),
                ('radius', models.IntegerField(verbose_name='Радиус галактики')),
                ('proximity_to_mw', models.IntegerField(verbose_name='Расстояние до Млечного Пути')),
            ],
            options={
                'verbose_name': 'Галактика',
                'verbose_name_plural': 'Галактики',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название системы')),
                ('proximity_to_center', models.IntegerField(verbose_name='Расстояние до центра галактики')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.galaxy', verbose_name='Название галактики')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(verbose_name='Радиус планеты')),
                ('name', models.CharField(max_length=30, verbose_name='Название планеты')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.system', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
    ]
